services:
  - type: web
    name: token-server
    env: docker
    plan: free
    envVars:
      - fromGroup: agent-example-env-group
    autoDeploy: true
    dockerfilePath: ./backend/token_server/Dockerfile
    buildContext: ./backend/token_server
